/*---------------------------------------------------------------------------
;
;
;
;
; 	FILE NAME  	: TP4_Lib_Divers.H
; 	TARGET MCUs	: C8051F020, 
; 	DESCRIPTION	: 
;
; 	REVISION 1.0
;
;---------------------------------------------------------------------------*/

#ifndef __TP4_Lib_Divers__
#define __TP4_Lib_Divers__


void Software_Delay_10ms(void);
void Software_Delay(unsigned int hundredth_second);

#endif